#!/usr/bin/perl
# -*- cperl -*-
use strict;

# TODO: store this info in the database, so it's easily customizable

our %format = (
               auto       => +{ label     => "Autodetect",
                                extension => "dat",
                                handler   => "auto",
                                sort      => 0,
                                mime      => ["application/octet-stream"],
                              },
               adobepdf   => +{ label     => "PDF (recommended)",
                                shortdesc => "PDF",
                                extension => "pdf",
                                handler   => undef, # undef means lp can handle it as-is.
                                sort      => 1,
                                mime      => ["application/pdf"],
                              },
               postscript => +{ label     => "PostScript",
                                extension => "ps",
                                handler   => undef,
                                sort      => 5,
                                mime      => ["application/postscript"],
                              },
               plaintext  => +{ label     => "Plain Text (ASCII or UTF-8)",
                                extension => "txt",
                                handler   => "text",
                                sort      => 50,
                                mime      => ["text/plain"],
                              },
               latinone   => +{ label     => "Plain Text (ISO Latin-1)",
                                extension => "txt",
                                handler   => "text",
                                sort      => 52,
                                charset   => 'iso-8859-1',
                              },
               cp437      => +{ label     => "Plain Text (codepage 437)",
                                extension => "txt",
                                handler   => "text",
                                sort      => 59,
                                charset   => 'cp437',# Requires Encode::Byte;
                              },
               msrtf      => +{ label     => "RichText Format (rtf)",
                                extension => "rtf",
                                handler   => "msoffice",
                                sort      => 65,
                                mime      => ["text/rtf"],
                              },
               html       => +{ label     => "HTML (self-contained)*" ,
                                extension => "html",
                                handler   => "html",
                                sort      => 70,
                                mime      => ["application/xhtml+xml",
                                              "text/html"],
                              },
               png        => +{ label     => "PNG image" ,
                                extension => "png",
                                handler   => "image",
                                sort      => 81,
                                mime      => ["image/png"],
                              },
               jpg        => +{ label     => "JPEG image",
                                extension => "jpg",
                                handler   => "image",
                                sort      => 82,
                                mime      => ["image/jpeg"],
                              },
               gif        => +{ label     => "GIF image",
                                extension => "gif",
                                handler   => "image",
                                sort      => 83,
                                mime      => ["image/gif"],
                              },
               svg        => +{ label     => "SVG image" ,
                                extension => "svg",
                                handler   => "image",
                                sort      => 87,
                                mime      => ["image/svg+xml"],
                              },
               xcf        => +{ label     => "Photo Editor format (Gimp, Photoshop, etc.)",
                                extension => "xcf",
                                #handler   => "gimp", # This probably requires script-fu use, but would handle virtually all .xcf and .psd images.
                                handler   => "imgfmt", # This is simpler, _if it works_.  We'll TRY it.
                                # xcftools is an additional possibility.  (There's also a corresponding psd-tools, but it requires pip, ugh.)
                                sort      => 88,
                                mime      => ["image/x-xcf", "image/x-photoshop", ],
                                noui      => 1, # Don't show in drop-down list; this is here only for autodetection purposes.
                              },
               bmp        => +{ label     => "Legacy Bitmap Image (BMP, TIFF, etc.)",
                                extension => "dat",
                                handler   => "imgfmt",
                                sort      => 89,
                                mime      => ["image/pcx", "image/tiff", "image/x-ms-bmp",
                                              "image/x-portable-pixmap", "image/x-xbitmap", "image/x-xpixmap"],
                                noui      => 1, # Don't show in drop-down list; this is here only for autodetection purposes.
                              },
               writer     => +{ label     => "OpenOffice.org Writer",
                                extension => "odt",
                                handler   => "openoffice",
                                sort      => 110,
                                mime      => ["application/vnd.oasis.opendocument.text"],
                              },
               msword     => +{ label     => "Microsoft Word 97 (doc)",
                                extension => "doc",
                                handler   => "msoffice",
                                sort      => 111,
                                mime      => ["application/msword"],
                              },
               mswordx    => +{ label     => "Microsoft Word (docx)",
                                extension => "docx",
                                handler   => "msoffice",
                                sort      => 112,
                                mime      => ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
                              },
               oocalc     => +{ label     => "OpenOffice.org Calc",
                                extension => "ods",
                                handler   => "openoffice",
                                sort      => 130,
                                mime      => ["application/vnd.oasis.opendocument.spreadsheet"],
                              },
               excel      => +{ label     => "Excel 97 (xls)",
                                extension => "xls",
                                handler   => "msoffice",
                                sort      => 131,
                                mime      => ["application/vnd.ms-excel"],
                              },
               excelx     => +{ label     => "Excel (xlsx)",
                                extension => "xlsx",
                                handler   => "msoffice",
                                sort      => 132,
                                mime      => ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
                              },
               impress    => +{ label     => "OpenOffice.org Impress",
                                extension => "odp",
                                handler   => "openoffice",
                                sort      => 150,
                                mime      => ["application/vnd.oasis.opendocument.presentation"],
                              },
               ppoint     => +{ label     => "PowerPoint 97 (ppt)",
                                extension => "ppt",
                                handler   => "msoffice",
                                sort      => 151,
                                mime      => ["application/vnd.ms-powerpoint"],
                              },
               ppointx    => +{ label     => "PowerPoint (pptx)",
                                extension => "pptx",
                                handler   => "msoffice",
                                sort      => 152,
                                mime      => ["application/vnd.openxmlformats-officedocument.presentationml.presentation"],
                              },
               oodraw     => +{ label     => "OpenOffice.org Draw",
                                extension => "odg",
                                handler   => "openoffice",
                                sort      => 190,
                                mime      => ["application/vnd.oasis.opendocument.graphics"],
                              },
               rfc822     => +{ label     => "rfc822",
                                extension => "eml",
                                handler   => "email",
                                sort      => 999,
                                mime      => ["message/rfc822"],
                              },
               gz         => +{ label     => "gzip",
                                extension => "gz",
                                handler   => "compression",
                                extract   => [$main::binpath{gunzip}, "-d", "-k"],
                                sort      => 9005,
                                mime      => ["application/gzip"],
                                noui      => 1, # Don't show in drop-down list; this format is here only for autodetection purposes.
                              },
               bz2        => +{ label     => "bzip2",
                                extension => "bz2",
                                handler   => "compression",
                                extract   => [$main::binpath{bunzip2}, "-d", "-k"],
                                sort      => 9006,
                                mime      => ["application/x-bzip2"],
                                noui      => 1, # Don't show in drop-down list; this format is here only for autodetection purposes.
                              },
               xz         => +{ label     => "xz",
                                extension => "xz",
                                handler   => "compression",
                                extract   => [$main::binpath{unxz}, "-d", "-k"],
                                sort      => 9007,
                                mime      => ["application/x-xz"],
                                noui      => 1, # Don't show in drop-down list; this format is here only for autodetection purposes.
                              },
               zip        => +{ label     => "PKWare ZIP archive",
                                extension => "zip",
                                handler   => "archive",
                                #extract   => ["/usr/bin/unzip"],
                                sort      => 9050,
                                mime      => ["application/zip"],
                                noui      => 1, # Don't show in drop-down list; this format is here only for autodetection purposes.
                              },
               tar        => +{ label     => "tarball",
                                extension => "tar",
                                handler   => "archive",
                                #extract   => ["/bin/tar", "-xf"],
                                sort      => 9055,
                                mime      => ["application/x-tar", "application/tar"],
                                noui      => 1, # Don't show in drop-down list; this format is here only for autodetection purposes.
                              },
              );

42;
